### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [ateeqsiddique/prj-rev-bwfs-dasmoto#2]
Instead of having to write shared properties such as `font-family: Helvetica;` separately for each element, you can write it once and include all the selectors separated by commas like so:

```css
h1, h2, .price {
  font-family: Helvetica;
}
```

https://github.com/ateeqsiddique/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/Resources/style.css
